### ISSUE TITLE
Windows 10, Visual Studio 14, Logitech M570

### ISSUE THREAD

**Issue by kwalker360** [tunnelvisionlabs/MouseNavigation#7] opened 2016-06-01 23:09 UTC
I just installed Mouse Navigation and it is not working with this configuration:

Windows 10
Visual Studio 14 (2015) Community Edition
Logitech M570 trackball

This is a new computer. Previously on a different laptop, I was using Windows 7 with the same Visual Studio and trackball and Mouse Navigation worked there.

Thanks,
Ken

**Comment by brittonbeckham** [comment] 2016-06-13 17:07
I just installed this (same setup, Windows 10, VS 2014 Pro, Logitech M705) -- mouse buttons do nothing

**Comment by sharwell** [comment] 2016-06-17 03:22
I'll mark this one as a duplicate of #5 :smile:

**Closed by sharwell** 2016-06-17 03:22 UTC

**Comment by kwalker360** [comment] 2016-06-17 16:23
Per the discussion in #5 , I uninstalled SetPoint and the buttons are now working in my Visual Studio 2015. Thanks!
