### ISSUE TITLE
Logitech M705 not working on VS 2013

### ISSUE THREAD

**Issue by sitecorejp** [tunnelvisionlabs/MouseNavigation#5] opened 2015-09-04 12:51 UTC
Hi, 

After I switched to VS2013 the mouse navigation stopped working. 
I have the latest version of MouseNavigation.

Thanks,

**Comment by olame** [comment] 2015-11-17 11:40
The same problem for Ultrathin Touch Mouse T630

**Comment by sharwell** [comment] 2015-11-17 11:51
I have a Logitech mouse, but not one of these. I'm not able to reproduce this issue.

The only thing I can think of is for someone who has experienced this to step through [`PostprocessMouseUp`](https://github.com/tunnelvisionlabs/MouseNavigation/blob/master/Tvl.VisualStudio.MouseNavigation/MouseNavigationProcessor.cs#L39) in the debugger and try to identify the problem.

**Comment by nickfloyd** [comment] 2015-11-17 22:30
@sharwell Thx for the plugin!  I'm running into the same thing with the Asus ROG GX850.  From what I can tell from debugging the extension in 2015 it looks like no event (overridden from MouseProcessorBase) fires when the side buttons are clicked (presumably XButton1 & XButton2).

I'm going to spin up a quick winforms app and try basic detection there if that does not work I'm going to give the Win32 Interop APIs a try.  My suspicion is that this is more of a hardware / driver issue or a limitation as to how much the VS TextEditor APIs can "see" (implementing the Win32 APIs will help me prove that).

My mouse config follows (Windows 10 / Visual Studio 2015)
![rog_mouse](https://cloud.githubusercontent.com/assets/139819/11226852/3c14b394-8d48-11e5-8fde-0bd9183eea4b.PNG)

**Comment by brittonbeckham** [comment] 2016-06-13 17:08
same issue with M705 mouse. Just tried today. Any progress on this?

**Comment by nickfloyd** [comment] 2016-06-13 17:47
@brittonbeckham no progress - I've been using a Logitech MX Master and it seems to work flawlessly.

**Comment by sharwell** [comment] 2016-06-14 01:49
@brittonbeckham "It shouldn't be too hard to debug this." It's open source but since I've never had another contributor on this particular project I can't be certain everything is in place to be extra easy.

But seriously, without one of these mice it's really only going to get fixed if someone who has one (and can reproduce this) figures out why it's not working and sends a pull request. :smile:

**Comment by brittonbeckham** [comment] 2016-06-16 17:06
I pulled the code down and ran the debugger. The event wasn't even being captured at all. I had a small hunch that it could be the Logitech mouse software called SetPoint that was rerouting the events. So I went ahead and uninstalled it and the events started being captured as expected. The settings I had on Logitech's SetPoint software for the back and forward buttons were **default settings** for the mouse (no custom actions specified), yet it still failed. 

Case and point, if you want this to work with Logitech, don't install SetPoint or uninstall it if you already have it installed. SetPoint doesn't give you much anyway and it's 70+ MB download (for mouse software -- definitely makes you wonder).

This probably resolves #7 as well. No PR needed :)

**Comment by sharwell** [comment] 2016-06-17 03:24
Thanks so much for investigating this @brittonbeckham. It's a *huge* help. If you get the chance, I'd be curious if you can find a way to tweak the SetPoint software so it does work with this extension. Some users could be relying on the software for other applications (e.g. gaming or some other customization), and it'd be nice to have an answer for them other than "uninstall it". Either way, I lean towards agreeing that this is a **wontfix** issue for this project, aside from perhaps a note in the documentation.

I'm leaving this issue open to update the readme to bring attention to this as a known issue for Logitech users who have SetPoint installed.

**Comment by jameselmer1** [comment] 2016-08-17 16:01
Hi,  I stumbled on this [MSDN answer](https://social.msdn.microsoft.com/Forums/en-US/09a7ebee-9567-4704-be88-de54a16ca99e/logitech-mouse-button-assignments-ignored-by-vs?forum=csharpide) and it has worked for me.  Simple summary is you have to run Logitech's SetPoint software as administrator for it to work with visual studio.  And inside of SetPoint, of course, you can assign the keystroke that maps to vs backward/forward commands.  Hope this helps.

**Comment by brittonbeckham** [comment] 2016-08-17 16:49
awesome, thanks. The Internets has all the answers, sometimes you just need
to dig deep enough to find it.


Britton
"Fix reason firmly in her seat, and call to her tribunal every fact, every
opinion. Question with boldness even the existence of a God; because, if
there be one, he must more approve of the homage of reason, than that of
blindfolded fear."*- Thomas Jefferson*

**Comment by mshahrouri** [comment] 2017-01-24 07:55
@sharwell thanks for your effort, but can you update the readme to reflect @jameselmer1 solution for Logitech owners

**Closed** 2017-01-25 11:55 UTC
Labels: bug, wontfix
